export enum LegoSetsActionTypes {
  FETCH_LEGOSETS_REQUEST = "FETCH_LEGOSETS_REQUEST",
  FETCH_LEGOSETS_SUCCESS = "FETCH_LEGOSETS_SUCCESS",
  FETCH_LEGOSETS_ERROR = "FETCH_LEGOSETS_ERROR",
  ADD_LEGOSETS = "ADD_LEGOSETS",
}
