export enum MinifiguresActionTypes {
  FETCH_MINIFIG_REQUEST = "FETCH_MINIFIG_REQUEST",
  FETCH_MINIFIG_SUCCESS = "FETCH_MINIFIG_SUCCESS",
  FETCH_MINIFIG_ERROR = "FETCH_MINIFIG_ERROR",
  ADD_MINIFIG = "ADD_MINIFIG",
}
